namespace TheNerdCollective.Integrations.Dar.GraphQL;

public static class GraphQlFieldLists
{
    public const string Bygning = """
        byg007Bygningsnummer
        byg021BygningensAnvendelse
        byg024AntalLejlighederMedKoekken
        byg025AntalLejlighederUdenKoekken
        byg026Opfoerelsesaar
        byg027OmTilbygningsaar
        byg029DatoForMidlertidigOpfoertBygning
        byg030Vandforsyning
        byg031Afloebsforhold
        byg032YdervaeggensMateriale
        byg033Tagdaekningsmateriale
        byg034SupplerendeYdervaeggensMateriale
        byg035SupplerendeTagdaekningsMateriale
        byg036AsbestholdigtMateriale
        byg037KildeTilBygningensMaterialer
        byg038SamletBygningsareal
        byg039BygningensSamledeBoligAreal
        byg040BygningensSamledeErhvervsAreal
        byg041BebyggetAreal
        byg042ArealIndbyggetGarage
        byg043ArealIndbyggetCarport
        byg044ArealIndbyggetUdhus
        byg045ArealIndbyggetUdestueEllerLign
        byg046SamletArealAfLukkedeOverdaekningerPaaBygningen
        byg047ArealAfAffaldsrumITerraenniveau
        byg048AndetAreal
        byg049ArealAfOverdaekketAreal
        byg050ArealAabneOverdaekningerPaaBygningenSamlet
        byg051Adgangsareal
        byg052BeregningsprincipCarportAreal
        byg053BygningsarealerKilde
        byg054AntalEtager
        byg055AfvigendeEtager
        byg056Varmeinstallation
        byg057Opvarmningsmiddel
        byg058SupplerendeVarme
        byg069Sikringsrumpladser
        byg070Fredning
        byg071BevaringsvaerdighedReference
        byg094Revisionsdato
        byg111StormraadetsOversvoemmelsesSelvrisiko
        byg112DatoForRegistreringFraStormraadet
        byg113Byggeskadeforsikringsselskab
        byg114DatoForByggeskadeforsikring
        byg119Udledningstilladelse
        byg121OmfattetAfByggeskadeforsikring
        byg122Gyldighedsdato
        byg123MedlemskabAfSpildevandsforsyning
        byg124PaabudVedrSpildevandsafledning
        byg125FristVedrSpildevandsafledning
        byg126TilladelseTilUdtraeden
        byg127DatoForTilladelseTilUdtraeden
        byg128TilladelseTilAlternativBortskaffelseEllerAfledning
        byg129DatoForTilladelseTilAlternativBortskaffelseEllerAfledning
        byg130ArealAfUdvendigEfterisolering
        byg131DispensationFritagelseIftKollektivVarmeforsyning
        byg132DatoForDispensationFritagelseIftKollektivVarmeforsyning
        byg133KildeTilKoordinatsaet
        byg134KvalitetAfKoordinatsaet
        byg135SupplerendeOplysningOmKoordinatsaet
        byg136PlaceringPaaSoeterritorie
        byg137BanedanmarkBygvaerksnummer
        byg140ServitutForUdlejningsEjendomDato
        byg150Gulvbelaegning
        byg151Frihoejde
        byg152AabenLukketKonstruktion
        byg153Konstruktionsforhold
        byg301TypeAfFlytning
        byg302Tilflytterkommune
        byg403OevrigeBemaerkningerFraStormraadet
        byg404Koordinat { type crs dimension wkt }
        byg406Koordinatsystem
        byg500Notatlinjer
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        ejerlejlighed
        forretningshaendelse
        forretningsomraade
        forretningsproces
        grund
        husnummer
        id_lokalId
        id_namespace
        jordstykke
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Enhed = """
        adresseIdentificerer
        bygning
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        enh008UUIDTilModerlejlighed
        enh020EnhedensAnvendelse
        enh023Boligtype
        enh024KondemneretBoligenhed
        enh025OprettelsesdatoForEnhedensIdentifikation
        enh026EnhedensSamledeAreal
        enh027ArealTilBeboelse
        enh028ArealTilErhverv
        enh030KildeTilEnhedensArealer
        enh031AntalVaerelser
        enh032Toiletforhold
        enh033Badeforhold
        enh034Koekkenforhold
        enh035Energiforsyning
        enh039AndetAreal
        enh041LovligAnvendelse
        enh042DatoForTidsbegraensetDispensation
        enh044DatoForDelvisIbrugtagningsTilladelse
        enh045Udlejningsforhold
        enh046OffentligStoette
        enh047IndflytningDato
        enh048GodkendtTomBolig
        enh051Varmeinstallation
        enh052Opvarmningsmiddel
        enh053SupplerendeVarme
        enh060EnhedensAndelFaellesAdgangsareal
        enh061ArealAfAabenOverdaekning
        enh062ArealAfLukketOverdaekningUdestue
        enh063AntalVaerelserTilErhverv
        enh065AntalVandskylledeToiletter
        enh066AntalBadevaerelser
        enh067Stoejisolering
        enh068FlexboligTilladelsesart
        enh069FlexboligOphoersdato
        enh070AabenAltanTagterrasseAreal
        enh071AdresseFunktion
        enh101Gyldighedsdato
        enh102HerafAreal1
        enh103HerafAreal2
        enh104HerafAreal3
        enh105SupplerendeAnvendelseskode1
        enh106SupplerendeAnvendelseskode2
        enh107SupplerendeAnvendelseskode3
        enh127FysiskArealTilBeboelse
        enh128FysiskArealTilErhverv
        enh500Notatlinjer
        etage
        forretningshaendelse
        forretningsomraade
        forretningsproces
        id_lokalId
        id_namespace
        kommunekode
        opgang
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Etage = """
        bygning
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        eta006BygningensEtagebetegnelse
        eta020SamletArealAfEtage
        eta021ArealAfUdnyttetDelAfTagetage
        eta022Kaelderareal
        eta023ArealAfLovligBeboelseIKaelder
        eta024EtagensAdgangsareal
        eta025Etagetype
        eta026ErhvervIKaelder
        eta500Notatlinjer
        forretningshaendelse
        forretningsomraade
        forretningsproces
        id_lokalId
        id_namespace
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Opgang = """
        adgangFraHusnummer
        bygning
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        forretningshaendelse
        forretningsomraade
        forretningsproces
        id_lokalId
        id_namespace
        kommunekode
        opg020Elevator
        opg021HusnummerFunktion
        opg500Notatlinjer
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Grund = """
        bestemtFastEjendom
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        forretningshaendelse
        forretningsomraade
        forretningsproces
        gru009Vandforsyning
        gru010Afloebsforhold
        gru021Udledningstilladelse
        gru022MedlemskabAfSpildevandsforsyning
        gru023PaabudVedrSpildevandsafledning
        gru024FristVedrSpildevandsafledning
        gru025TilladelseTilUdtraeden
        gru026DatoForTilladelseTilUdtraeden
        gru027TilladelseTilAlternativBortskaffelseEllerAfledning
        gru028DatoForTilladelseTilAlternativBortskaffelseEllerAfledning
        gru029DispensationFritagelseIftKollektivVarmeforsyning
        gru030DatoForDispensationFritagelseIftKollektivVarmeforsyning
        gru500Notatlinjer
        husnummer
        id_lokalId
        id_namespace
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string GrundJordstykke = """
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        forretningshaendelse
        forretningsomraade
        forretningsproces
        grund
        id_lokalId
        id_namespace
        jordstykke
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Ejendomsrelation = """
        bfeNummer
        bygningPaaFremmedGrund
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        ejendommensEjerforholdskode
        ejendomsnummer
        ejendomstype
        ejerlejlighed
        ejerlejlighedsnummer
        forretningshaendelse
        forretningsomraade
        forretningsproces
        id_lokalId
        id_namespace
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        samletFastEjendom
        status
        tinglystAreal
        virkningFra
        virkningsaktoer
        virkningTil
        vurderingsejendomsnummer
        """;

    public const string BygningEjendomsrelation = """
        bygning
        bygningPaaFremmedGrund
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        forretningshaendelse
        forretningsomraade
        forretningsproces
        id_lokalId
        id_namespace
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string TekniskAnlaeg = """
        bygning
        bygningPaaFremmedGrund
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        ejerlejlighed
        enhed
        forretningshaendelse
        forretningsomraade
        forretningsproces
        grund
        husnummer
        id_lokalId
        id_namespace
        jordstykke
        kommunekode
        registreringFra
        registreringsaktoer
        registreringTil
        status
        tek007Anlaegsnummer
        tek020Klassifikation
        tek021FabrikatType
        tek022EksternDatabase
        tek023EksternNoegle
        tek024Etableringsaar
        tek025TilOmbygningsaar
        tek026StoerrelsesklasseOlietank
        tek027Placering
        tek028SloejfningOlietank
        tek030Fabrikationsnummer
        tek031Typegodkendelsesnummer
        tek032Stoerrelse
        tek033Type
        tek034IndholdOlietank
        tek035SloejfningsfristOlietank
        tek036Rumfang
        tek037Areal
        tek038Hoejde
        tek039Effekt
        tek040Fredning
        tek042Revisionsdato
        tek045Koordinatsystem
        tek067Fabrikationsaar
        tek068Materiale
        tek069SupplerendeIndvendigKorrosionsbeskyttelse
        tek070DatoForSenestUdfoerteSupplerendeIndvendigKorrosionsbeskyttelse
        tek072Sloejfningsaar
        tek073Navhoejde
        tek074Vindmoellenummer
        tek075Rotordiameter
        tek076KildeTilKoordinatsaet
        tek077KvalitetAfKoordinatsaet
        tek078SupplerendeOplysningOmKoordinatsaet
        tek101Gyldighedsdato
        tek102FabrikatVindmoelle
        tek103FabrikatOliefyr
        tek104FabrikatSolcelleanlaegSolvarme
        tek105OverdaekningTank
        tek106InspektionsdatoTank
        tek107PlaceringPaaSoeterritorie
        tek109Koordinat { type crs dimension wkt }
        tek110Driftstatus
        tek111DatoForSenesteInspektion
        tek112InspicerendeVirksomhed
        tek500Notatlinjer
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Kommuneinddeling = """
        id_lokalId
        navn
        kommunekode
        regionLokalid
        """;

    public const string Regionsinddeling = """
        id_lokalId
        navn
        regionskode
        """;

    public const string Husnummer = """
        adgangsadressebetegnelse
        adgangspunkt
        adgangTilBygning
        adgangTilTekniskAnlaeg
        afstemningsomraade
        datafordelerOpdateringstid
        datafordelerRegisterImportSequenceNumber
        datafordelerRowId
        datafordelerRowVersion
        forretningshaendelse
        forretningsomraade
        forretningsproces
        geoDanmarkBygning
        husnummerretning { type crs dimension wkt }
        husnummertekst
        id_lokalId
        id_namespace
        jordstykke
        kommuneinddeling
        menighedsraadsafstemningsomraade
        navngivenVej
        placeretPaaForeloebigtJordstykke
        postnummer
        registreringFra
        registreringsaktoer
        registreringTil
        sogneinddeling
        status
        supplerendeBynavn
        vejmidte
        vejpunkt
        virkningFra
        virkningsaktoer
        virkningTil
        """;

    public const string Postnummer = """
        id_lokalId
        postnr
        navn
        status
        """;

}
