using System.IO.Compression;
using System.Text;

namespace TheNerdCollective.MudComponents.DesignTokens;

/// <summary>Builds a designer ↔ developer handoff ZIP from the active brand pack.</summary>
public static class NerdDesignHandoffTools
{
    public static byte[] CreateZip(
        NerdDesignHandoffRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(request.Options);

        var options = request.Options;
        var pack = NerdTokenPack.FromOptions(options, request.ClientId);
        var parity = NerdDesignParityTools.Evaluate(options, request.IncludeExtendedRecipes);

        using var memory = new MemoryStream();
        using (var archive = new ZipArchive(memory, ZipArchiveMode.Create, leaveOpen: true))
        {
            WriteEntry(archive, "token-pack.json", pack.ToJson());
            WriteEntry(archive, "tokens.json", NerdDesignTokenTools.ExportJson(options));
            WriteEntry(archive, "tokens.css", MudBlazorDesignTokenCssGenerator.Generate(options));
            WriteEntry(archive, "DESIGN.md", NerdDesignTokenTools.ExportStitchDesignMd(options, request.TypographyRoles));
            WriteEntry(archive, "WCAG-REPORT.md", BuildWcagReport(options, parity));
            WriteEntry(archive, "README-HANDOFF.md", BuildReadme(options, request));

            if (!string.IsNullOrWhiteSpace(request.TypographyJson))
            {
                WriteEntry(archive, "typography.json", request.TypographyJson);
            }
        }

        return memory.ToArray();
    }

    private static string BuildReadme(NerdDesignTokenOptions options, NerdDesignHandoffRequest request)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"# {options.ActiveBrandPackId ?? options.Prefix} — brand handoff");
        builder.AppendLine();
        builder.AppendLine("Generated by Nerd Token Studio.");
        builder.AppendLine();
        builder.AppendLine("## Files");
        builder.AppendLine("- `token-pack.json` — full pack (colors, aliases, recipes, shell, frameworkDefaults)");
        builder.AppendLine("- `tokens.css` — MudBlazor-ready CSS");
        builder.AppendLine("- `tokens.json` — portable token export");
        builder.AppendLine("- `DESIGN.md` — Stitch-compatible design handoff");
        builder.AppendLine("- `WCAG-REPORT.md` — contrast and parity summary");
        if (!string.IsNullOrWhiteSpace(request.TypographyJson))
        {
            builder.AppendLine("- `typography.json` — responsive typography roles");
        }

        if (!string.IsNullOrWhiteSpace(request.DesignGuideUrl))
        {
            builder.AppendLine();
            builder.AppendLine($"## Live design guide");
            builder.AppendLine(request.DesignGuideUrl);
        }

        return builder.ToString();
    }

    private static string BuildWcagReport(NerdDesignTokenOptions options, NerdDesignParityResult parity)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"# WCAG & parity report — {options.Prefix}");
        builder.AppendLine();
        builder.AppendLine($"**Parity score:** {parity.Score}/100");
        builder.AppendLine();
        foreach (var metric in parity.Metrics)
        {
            builder.AppendLine($"- **{metric.Name}** ({metric.Score}/100): {metric.Detail}");
        }

        builder.AppendLine();
        builder.AppendLine("## Token accessibility");
        foreach (var result in NerdDesignTokenTools.CheckAccessibility(options))
        {
            builder.AppendLine(
                $"- `{result.Name}` light: {result.Light.ContrastRatio:0.0}:1 AA {(result.Light.MeetsAa ? "pass" : "fail")}; " +
                $"dark: {result.Dark.ContrastRatio:0.0}:1 AA {(result.Dark.MeetsAa ? "pass" : "fail")}");
        }

        return builder.ToString();
    }

    private static void WriteEntry(ZipArchive archive, string name, string content)
    {
        var entry = archive.CreateEntry(name, CompressionLevel.Optimal);
        using var entryStream = entry.Open();
        using var writer = new StreamWriter(entryStream, Encoding.UTF8);
        writer.Write(content);
    }
}

public sealed class NerdDesignHandoffRequest
{
    public required NerdDesignTokenOptions Options { get; init; }

    public string ClientId { get; init; } = "client";

    public string? TypographyJson { get; init; }

    public IReadOnlyDictionary<string, string>? TypographyRoles { get; init; }

    public string? DesignGuideUrl { get; init; }

    public bool IncludeExtendedRecipes { get; init; }
}
